apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic
spec:
  selector:
    matchLabels:
      app: clinic
  template:
    metadata:
      labels:
        app: clinic
    spec:
      containers:
      - name: pet-clinic
        image: amay1794/petclinic
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: clinic-svc
spec:
  type: NodePort
  selector:
    app: clinic
  ports:
  - port: 8081
    targetPort: 8080
    nodePort: 30001

